# Site settings
title: Zhitao's octopress blog
email: cztchoice#gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You are what you do. Not what you think.
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
baseurl: "/cztchoice-octopress/" # the subpath of your site, e.g. /blog/
url: "http://www.zhitao.me/" # the base hostname & protocol for your site
twitter_username: cztchoice
github_username:  cztchoice

# Build settings
markdown: kramdown

exclude: []
